version: '2'
services:
  postgres-datavolume:
    image: postgres
    entrypoint: chown -R postgres:postgres /var/lib/postgresql/data    
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=petstore
      - POSTGRES_PASSWORD=petstore
      - POSTGRES_DB=petstore
    volumes_from:
    - postgres-datavolume

  conf:
    build: ./dockerconf
    volumes: 
      - conf:/conf

  petapi:
    image: dmetzler/pet-api
    command: server /conf/petapi-conf.yml
    links:
    - postgres:postgres
    volumes_from:
    - conf
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local
  conf:
    driver: local
